# Generated by Django 2.2 on 2019-04-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('preparation', models.TextField()),
                ('uploader', models.CharField(max_length=200)),
                ('plain_text_ingredients', models.TextField()),
                ('estimated_price', models.IntegerField()),
                ('imagePath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DishInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recommender.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unitaryPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('role', models.BooleanField()),
                ('hashedPassword', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('follow', models.ManyToManyField(to='food_recommender.User')),
                ('liked_dishes', models.ManyToManyField(through='food_recommender.DishInterest', to='food_recommender.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dishes_in_menu', models.ManyToManyField(to='food_recommender.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='dishinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recommender.User'),
        ),
        migrations.CreateModel(
            name='DishIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recommender.Dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recommender.Ingredient')),
            ],
        ),
    ]
