# Generated by Django 2.1.7 on 2019-04-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0005_auto_20190408_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish',
            field=models.ManyToManyField(to='food_recommender.Dish'),
        ),
        migrations.AddField(
            model_name='user',
            name='dish',
            field=models.ManyToManyField(through='food_recommender.DishInterest', to='food_recommender.Dish'),
        ),
    ]
