# Generated by Django 2.1.7 on 2019-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0007_auto_20190409_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='dish',
            new_name='dishes_in_menu',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dish',
            new_name='liked_dishes',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to='food_recommender.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hashedPassword',
            field=models.CharField(max_length=200),
        ),
    ]
