# Generated by Django 2.1.7 on 2019-04-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0011_dish_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(to='food_recommender.User'),
        ),
    ]
