# Generated by Django 2.1.7 on 2019-04-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishingredients',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='dishinmenu',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishinmenu',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ManyToManyField(to='food_recommender.Restaurant'),
        ),
        migrations.DeleteModel(
            name='DishIngredients',
        ),
        migrations.DeleteModel(
            name='DishInMenu',
        ),
    ]
