# Generated by Django 2.1.7 on 2019-04-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0002_auto_20190408_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recommender.Dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_recommender.Ingredient')),
            ],
        ),
    ]
