# Generated by Django 2.1.7 on 2019-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0003_dishingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ManyToManyField(through='food_recommender.DishInterest', to='food_recommender.User'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(through='food_recommender.DishIngredients', to='food_recommender.Dish'),
        ),
    ]
