# Generated by Django 2.1.7 on 2019-04-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0012_auto_20190415_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='follow',
        ),
    ]
