# Generated by Django 2.2 on 2019-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommender', '0013_auto_20190415_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='estimated_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='plain_text_ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
